version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt-get install npm
      - npm install

  
  build:
    commands:
      - npm run build-dev
  
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build